before_script: 
 - sudo ls /home/
 - sudo useradd --create-home -s /bin/bash stratos
 - sudo sh -c 'echo "stratos:stratos" | chpasswd'
 - sudo sh -c 'echo "stratos ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/stratos'
 - sudo sh -c 'echo "Defaults:stratos secure_path=/sbin:/usr/sbin:/usr/bin:/bin:/usr/local/sbin:/usr/local/bin" >> /etc/sudoers.d/stratos'
 - sudo chown 0440 /etc/sudoers.d/stratos
script:
 - sudo -iE -u stratos sh -c 'echo "" | bash -x /home/travis/build/snowch/devcloud-script/stratos_dev.sh -f'
