before_script: 
 - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
 - sudo useradd --create-home -s /bin/bash stratos
 - sudo sh -c 'echo "stratos:stratos" | chpasswd'
 - sudo sh -c 'umask 0226; echo "stratos ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/stratos'
 - sudo sh -c 'echo "Defaults:stratos secure_path=/sbin:/usr/sbin:/usr/bin:/bin:/usr/local/sbin:/usr/local/bin" >> /etc/sudoers.d/stratos'
script:
 - sudo -iE -u stratos sh -c 'bash -x /home/travis/build/snowch/devcloud-script/stratos_dev.sh -f'
 - sudo -iE -u stratos sh -c 'bash /home/travis/build/snowch/devcloud-script/stratos_dev.sh -t'
